name: Bearer

on:
  push:
    branches:
      - master

permissions:
  contents: read
  # Add the security-events permission for Advanced Security
  # security-events: write

jobs:
  rule_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        with:
          api-key: ${{ secrets.BEARER_TOKEN }}
          # Include these two options for Advanced Security
          # format: sarif
          # output: results.sarif
      
      # Add a new step to upload the SARIF file for Advanced Security
      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: results.sarif

